# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-04 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='average_number_patient_visits',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='average_patient_stay_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='number_patient_visits',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avg_hospital_visit_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='number_hospital_visits',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temp_check_in_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temp_check_out_time',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='times_prescribed',
        ),
        migrations.AddField(
            model_name='patient',
            name='current_hospital',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 4, 14, 12, 32, 817966, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
    ]
