# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-06 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20161104_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('is_released', models.BooleanField(default=False)),
                ('results', models.FileField(upload_to='tests/')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='average_number_hospital_visits_per_patient',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='average_patient_stay_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='number_patient_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='number_patients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='avg_hospital_visit_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='checked_in_hospital',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_hospital+', to='health.Hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_hospital_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='temp_check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 22, 36, 21, 609645, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='patient',
            name='temp_check_out_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 22, 36, 21, 609645, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='prescription',
            name='times_prescribed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 23, 36, 21, 625270, tzinfo=utc), verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Patient'),
        ),
    ]
